# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 458cd614139ef1756780b2e96482a891869fe8a77b633846b3840f0fd60dfa7362fdb4a18284b190c507a5387adaaae8c8768c2f39046cdd99ec24426ad2f140

test:
  secret_key_base: 0643f3f6929536908bf4e497e24c59e670093586706f8c75ba2f52d64889722a4109b7d7e21a09aa52bd1cf7412a26ac8ef2f411c0d7d4b59666f87184414780

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
